app:
  scheduler:
    enable: true
    interval: 1000
    force-check-delay: 1000
    link-checking-frequency: 3m

  github:
    base-url: https://api.github.com/
    back-off:
      delay: 3s
      policy: linear
      max-attempts: 3
      additional-statuses:
        - 429
        - 408

  stackoverflow:
    base-url: https://api.stackexchange.com/
    back-off:
      delay: 3s
      policy: linear
      max-attempts: 3
      additional-statuses:
        - 429
        - 408

  bot:
    base-url: http://localhost:8090/
    back-off:
      delay: 500ms
      policy: exponential
      max-attempts: 10
      multiplier: 2
      additional-statuses:
        - 429

  data-base-access-type: jpa
  rate-limiting:
    requests-limit: 15
    time-duration: 1m
  sending-method: queue
  kafka:
    producer-topic: edu.tinkoff.updates
spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: 127.0.0.1:9092
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html

