app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000
  base-urls:
    git-hub-api: https://api.github.com/
    stack-overflow-api: https://api.stackexchange.com/
    bot-api: http://localhost:8090/

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html

