app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper:
    base-url: http://localhost:8080/
    back-off:
      delay: 1s
      policy: exponential
      max-attempts: 5
      multiplier: 2
      additional-statuses:
        - 408
        - 429
  rate-limiting:
    requests-limit: 20
    time-duration: 1m
  kafka:
    consumer-topic: ru.andryxx.botupdates
spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: "instance.telegrambot"

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html

management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: /metrics
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
