app:
  telegram-token: ${TELEGRAM_TOKEN}
  scrapper-api-base-url: http://localhost:8080/

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html

