/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.tables;


import edu.java.scrapper.domain.jooq.DefaultSchema;
import edu.java.scrapper.domain.jooq.Keys;
import edu.java.scrapper.domain.jooq.tables.records.LinkChatAssignmentRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinkChatAssignment extends TableImpl<LinkChatAssignmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINK_CHAT_ASSIGNMENT</code>
     */
    public static final LinkChatAssignment LINK_CHAT_ASSIGNMENT = new LinkChatAssignment();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<LinkChatAssignmentRecord> getRecordType() {
        return LinkChatAssignmentRecord.class;
    }

    /**
     * The column <code>LINK_CHAT_ASSIGNMENT.ID</code>.
     */
    public final TableField<LinkChatAssignmentRecord, Long> ID = createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>LINK_CHAT_ASSIGNMENT.LINK_ID</code>.
     */
    public final TableField<LinkChatAssignmentRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LINK_CHAT_ASSIGNMENT.CHAT_ID</code>.
     */
    public final TableField<LinkChatAssignmentRecord, Long> CHAT_ID = createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private LinkChatAssignment(Name alias, Table<LinkChatAssignmentRecord> aliased) {
        this(alias, aliased, null);
    }

    private LinkChatAssignment(Name alias, Table<LinkChatAssignmentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LINK_CHAT_ASSIGNMENT</code> table reference
     */
    public LinkChatAssignment(String alias) {
        this(DSL.name(alias), LINK_CHAT_ASSIGNMENT);
    }

    /**
     * Create an aliased <code>LINK_CHAT_ASSIGNMENT</code> table reference
     */
    public LinkChatAssignment(Name alias) {
        this(alias, LINK_CHAT_ASSIGNMENT);
    }

    /**
     * Create a <code>LINK_CHAT_ASSIGNMENT</code> table reference
     */
    public LinkChatAssignment() {
        this(DSL.name("LINK_CHAT_ASSIGNMENT"), null);
    }

    public <O extends Record> LinkChatAssignment(Table<O> child, ForeignKey<O, LinkChatAssignmentRecord> key) {
        super(child, key, LINK_CHAT_ASSIGNMENT);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<LinkChatAssignmentRecord, Long> getIdentity() {
        return (Identity<LinkChatAssignmentRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<LinkChatAssignmentRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_6;
    }

    @Override
    @NotNull
    public List<UniqueKey<LinkChatAssignmentRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_LINK_CHAT_ASSIGNMENT);
    }

    @Override
    @NotNull
    public List<ForeignKey<LinkChatAssignmentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_60, Keys.CONSTRAINT_604);
    }

    private transient Link _link;
    private transient Chat _chat;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.CONSTRAINT_60);

        return _link;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.CHAT</code> table.
     */
    public Chat chat() {
        if (_chat == null)
            _chat = new Chat(this, Keys.CONSTRAINT_604);

        return _chat;
    }

    @Override
    @NotNull
    public LinkChatAssignment as(String alias) {
        return new LinkChatAssignment(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public LinkChatAssignment as(Name alias) {
        return new LinkChatAssignment(alias, this);
    }

    @Override
    @NotNull
    public LinkChatAssignment as(Table<?> alias) {
        return new LinkChatAssignment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinkChatAssignment rename(String name) {
        return new LinkChatAssignment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinkChatAssignment rename(Name name) {
        return new LinkChatAssignment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinkChatAssignment rename(Table<?> name) {
        return new LinkChatAssignment(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
