/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq;


import edu.java.scrapper.domain.jooq.tables.Chat;
import edu.java.scrapper.domain.jooq.tables.Link;
import edu.java.scrapper.domain.jooq.tables.LinkChatAssignment;
import edu.java.scrapper.domain.jooq.tables.records.ChatRecord;
import edu.java.scrapper.domain.jooq.tables.records.LinkChatAssignmentRecord;
import edu.java.scrapper.domain.jooq.tables.records.LinkRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 = Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] { Chat.CHAT.ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] { Link.LINK.ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] { Link.LINK.URL }, true);
    public static final UniqueKey<LinkChatAssignmentRecord> CONSTRAINT_6 = Internal.createUniqueKey(LinkChatAssignment.LINK_CHAT_ASSIGNMENT, DSL.name("CONSTRAINT_6"), new TableField[] { LinkChatAssignment.LINK_CHAT_ASSIGNMENT.ID }, true);
    public static final UniqueKey<LinkChatAssignmentRecord> UNIQUE_LINK_CHAT_ASSIGNMENT = Internal.createUniqueKey(LinkChatAssignment.LINK_CHAT_ASSIGNMENT, DSL.name("UNIQUE_LINK_CHAT_ASSIGNMENT"), new TableField[] { LinkChatAssignment.LINK_CHAT_ASSIGNMENT.LINK_ID, LinkChatAssignment.LINK_CHAT_ASSIGNMENT.CHAT_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinkChatAssignmentRecord, LinkRecord> CONSTRAINT_60 = Internal.createForeignKey(LinkChatAssignment.LINK_CHAT_ASSIGNMENT, DSL.name("CONSTRAINT_60"), new TableField[] { LinkChatAssignment.LINK_CHAT_ASSIGNMENT.LINK_ID }, Keys.CONSTRAINT_2, new TableField[] { Link.LINK.ID }, true);
    public static final ForeignKey<LinkChatAssignmentRecord, ChatRecord> CONSTRAINT_604 = Internal.createForeignKey(LinkChatAssignment.LINK_CHAT_ASSIGNMENT, DSL.name("CONSTRAINT_604"), new TableField[] { LinkChatAssignment.LINK_CHAT_ASSIGNMENT.CHAT_ID }, Keys.CONSTRAINT_1, new TableField[] { Chat.CHAT.ID }, true);
}
